export const universities = [
    "ALKAN Health Science Business and Technology College",
    "Adama University",
    "Addis Ababa Commercial College",
    "Addis Ababa Science and Technology University",
    "Addis Ababa University",
    "Addis College",
    "Addis Continental Institute of Public Health",
    "Adigrat University",
    "Admas University College",
    "Aksum University",
    "Ambo University",
    "Arba Minch University",
    "Arsi University",
    "Assosa University",
    "Axum University",
    "Bahir Dar University",
    "BITS College",
    "Bonga University",
    "Borena University",
    "Bule Hora University",
    "City University College",
    "Closys College",
    "Dandii Boruu College",
    "Debark University",
    "Debre Berhan University",
    "Debre Markos University",
    "Debre Tabor University",
    "Defence University College of Engineering",
    "Dembi Dolo University",
    "Dessie Teacher's Education College",
    "Dilla University",
    "Dire Dawa University",
    "Dynamic International University College",
    "Ethiopian Catholic University",
    "Ethiopian Civil Service University",
    "Ethiopian Institute of Architecture, Building Construction and City Development",
    "Gambella University",
    "Grace College of Business and Computer Science",
    "Haramaya University",
    "Hawassa University",
    "Infonet College",
    "Injibara University",
    "International Leadership Institute",
    "Jethro Leadership & Management Institute",
    "Jigjiga University",
    "Jimma College of Teachers Education",
    "Jimma Teachers College",
    "Jimma University",
    "Jinka University",
    "Kebri Dehar University",
    "Kotebe Education University",
    "Kunuz College",
    "Madda Walabu University",
    "Mattu University",
    "Mekdela Amba University",
    "Mekelle Institute of Technology",
    "Mekelle University",
    "Mizan–Tepi University",
    "New Generation University College",
    "Oda Bultum University",
    "PESC Information Systems College",
    "Raya University",
    "Rift Valley University",
    "Royal College/Ethiopia",
    "Samara University",
    "Selale University",
    "Select College",
    "Semera University",
    "St. Mary's University",
    "St. Paul's Hospital Millennium Medical College",
    "Unity University",
    "University of Gondar",
    "Urban Planning College (Ecole)",
    "Wachemo University",
    "Warabe University",
    "Washera College",
    "Wolaita Sodo University",
    "Woldia University",
    "Wolkite University",
    "Wollega University",
    "Wollo University"
];

export const departments = [
    "Accounting & Finance",
    "Administrative Services Management",
    "African Studies",
    "Amharic Language, Literature and Folklore",
    "Archaeology and Heritage Management",
    "Architecture and Urban Planning",
    "Biomedical Engineering",
    "Business Administration and Information Systems",
    "Center for Environmental Science",
    "Center for Environmental and Development Studies",
    "Center for Federal Studies",
    "Center for Food Security Studies",
    "Center for Gender Studies",
    "Center for Human Rights",
    "Center for Population Studies and Research",
    "Center for Regional and Local Development Studies",
    "Center for Rural Development Studies",
    "Chemistry",
    "Civil Engineering",
    "Computer Science",
    "Curriculum and Teachers Professionals Development Studies",
    "Earth Science",
    "Economics",
    "Educational Planning & Management",
    "Electrical and Computer Engineering",
    "Finance and Development Economics",
    "Foreign Language and Literature",
    "General Biology",
    "Geography and Environmental Studies",
    "History",
    "Hydraulics and Water Resources Engineering",
    "Information Science",
    "Information Technology",
    "Language Studies Center",
    "Lexicography, Terminology and Translation Center",
    "Linguistics",
    "Management",
    "Marketing Management",
    "Material Science Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Oromo Language, Literature and Folklore",
    "Philology Center",
    "Philosophy",
    "Plant Biology and Biodiversity",
    "Political Science and International Relations",
    "Procurement and Supply Chain Management Program Unit",
    "Public Administration",
    "Physics",
    "School of Journalism and Communication",
    "School of Law",
    "School of Psychology",
    "Science and Mathematics Education",
    "Social and Cultural Studies Center",
    "Social Anthropology",
    "Social Science and Language Education",
    "Social Work",
    "Sociology",
    "Software Engineering",
    "Special Needs Department",
    "Sport",
    "Statistics",
    "Tigrigna Language, Literature and Folklore",
    "Water Supply & Engineering",
    "Zoological Science"
  ];
  
export const years = [
    "1st Year",
    "2nd Year",
    "3rd Year",
    "4th Year",
    "5th Year",
    "6th Year",
    "7th Year",
    "8th Year",
]